name: Create EC2 Instance

on:
  workflow_dispatch:

jobs:
  create-ec2:
    runs-on: ubuntu-latest
    outputs:
      instance_id: ${{ steps.launch.outputs.instance_id }}
      public_ip: ${{ steps.get_ip.outputs.public_ip }}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Launch EC2 instance
        id: launch
        run: |
          IMAGE_ID=$(aws ec2 describe-images \
            --owners 099720109477 \
            --filters "Name=name,Values=ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*" \
                      "Name=state,Values=available" \
            --query "sort_by(Images, &CreationDate)[-1].ImageId" \
            --output text)

          INSTANCE_ID=$(aws ec2 run-instances \
            --image-id $IMAGE_ID \
            --count 1 \
            --instance-type t2.micro \
            --key-name devops-key \  # Your existing key pair
            --security-groups default \
            --query 'Instances[0].InstanceId' \
            --output text)

          echo "instance_id=$INSTANCE_ID" >> $GITHUB_OUTPUT

      - name: Wait for EC2 to be running
        run: aws ec2 wait instance-running --instance-ids ${{ steps.launch.outputs.instance_id }}

      - name: Get Public IP
        id: get_ip
        run: |
          PUBLIC_IP=$(aws ec2 describe-instances \
            --instance-ids ${{ steps.launch.outputs.instance_id }} \
            --query "Reservations[0].Instances[0].PublicIpAddress" \
            --output text)
          echo "public_ip=$PUBLIC_IP" >> $GITHUB_OUTPUT
          echo "EC2 public IP: $PUBLIC_IP"
