name: Deploy EC2 Ubuntu Instance

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change to your region

      - name: Create key file for SSH access
        run: |
          echo "${{ secrets.DEVOPS_KEY }}" > devops-key-1.pem
          chmod 400 devops-key-1.pem

      - name: Launch Ubuntu EC2 Instance
        id: ec2
        run: |
          INSTANCE_ID=$(aws ec2 run-instances \
            --image-id ami-0c02fb55956c7d316 \  # Ubuntu 20.04 LTS in us-east-1
            --count 1 \
            --instance-type t2.micro \
            --key-name devops-key \
            --security-groups default \
            --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=GitHubEC2}]' \
            --query 'Instances[0].InstanceId' \
            --output text)

          echo "Instance ID: $INSTANCE_ID"

          # Wait for instance to be running
          aws ec2 wait instance-running --instance-ids $INSTANCE_ID

          # Get public IP
          PUBLIC_IP=$(aws ec2 describe-instances \
            --instance-ids $INSTANCE_ID \
            --query 'Reservations[0].Instances[0].PublicIpAddress' \
            --output text)

          echo "EC2_PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV
          echo "Instance public IP: $PUBLIC_IP"

      # - name: Output Public IP
      #   run: echo "EC2 Public IP: $EC2_PUBLIC_IP"
        
